on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", "STANDARDS.md", "LICENSE", "CHANGELOG.md"]
  pull_request:
jobs:
  check-formatting:
    name: "Check source code formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 9.2
          cabal-version: latest
      - name: Get fourmolu
        uses: actions/checkout@v2
        with:
          repository: parsonsmatt/fourmolu
          path: ./fourmolu
          ref: 30ffbe3491e71a6d81620bd66fd842c3ef3f8bd2
      - name: Configure fourmolu
        working-directory: fourmolu
        run: cabal new-configure -w ghc --disable-optimization
      - name: Freeze
        working-directory: fourmolu
        run: cabal new-freeze
      - name: Cache
        uses: actions/cache@v2.1.3
        env:
          V: 0
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ./fourmolu/dist-newstyle
          key: ${{ env.V }}-${{ hashFiles('./fourmolu/cabal.project.freeze') }}
          restore-keys: ${{ env.V }}-
      - name: Install fourmolu
        working-directory: fourmolu
        run: cabal new-install --install-method=copy --installdir=${{ runner.temp }} --overwrite-policy=always exe:fourmolu
      - name: Check formatting
        run: ./.github/format.sh ${{ runner.temp }}/fourmolu
