on:
  push:
    branches: ["main", "staging"]
    paths-ignore: ["README.md", "STANDARDS.md", "LICENSE", "CHANGELOG.md"]
  pull_request:

jobs:
  flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tasks: 
          - plutarch-quickcheck
          - formatCheck
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: cachix/install-nix-action@v16
        name: Set up Nix and IOHK caches
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v10
        with:
          name: mlabs
          authToken: ${{ secrets.CACHIX_KEY }}

      - run: nix build .#checks.x86_64-linux.${{ matrix.tasks }}
        name: Run '${{ matrix.tasks }}' from flake.nix
